// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oreolder.Models;

public partial class Job
{
    public long Id { get; set; }

    public long CustomerId { get; set; }

    public int JobTypeId { get; set; }

    public string LinkJobId { get; set; }

    public long? BillingAddressId { get; set; }

    public long PaymentMethodId { get; set; }

    public long? StoreId { get; set; }

    public long? AdTypeId { get; set; }

    public long? EquipmentId { get; set; }

    public int? JobStatusId { get; set; }

    public int? StateId { get; set; }

    public int CountryId { get; set; }

    public long? CountyId { get; set; }

    public int? AddressTypeId { get; set; }

    public string ZipCode { get; set; }

    public bool IsAuto { get; set; }

    public string Ponumber { get; set; }

    public string WorkOrder2 { get; set; }

    public string Phone { get; set; }

    public string AlternatePhone { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string Street { get; set; }

    public string ApartmentSuite { get; set; }

    public long BookedByUserId { get; set; }

    public string BuzzerCode { get; set; }

    public string Fax { get; set; }

    public string EmailAddress { get; set; }

    public string CalledInBy { get; set; }

    public string ContactPerson { get; set; }

    public string ContactPersonPhone { get; set; }

    public string ContactPersonEmail { get; set; }

    public decimal? Nteamount { get; set; }

    public int? DateIntervalType { get; set; }

    public DateTime? OnDate { get; set; }

    public TimeSpan? FromTime { get; set; }

    public TimeSpan? ToTime { get; set; }

    public DateTime? DispatchedTime { get; set; }

    public int? Year { get; set; }

    public string Make { get; set; }

    public string Model { get; set; }

    public string Color { get; set; }

    public string Description { get; set; }

    public bool? IsEmergency { get; set; }

    public string Ask { get; set; }

    public string Notes { get; set; }

    public bool EstimatePrinted { get; set; }

    public bool EstimateEmailed { get; set; }

    public bool? IsCow { get; set; }

    public bool TaxExempt { get; set; }

    public bool IsBillingSameAsServiceAddress { get; set; }

    public DateTime CreatedOn { get; set; }

    public long CreatedByUserId { get; set; }

    public DateTime LastUpdateOn { get; set; }

    public long LastUpdatedByUserId { get; set; }

    public bool Locked { get; set; }

    public string AdTypeOtherOption { get; set; }

    public string AdTypeWebSource { get; set; }

    public bool AlertedOniPhone { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longtitude { get; set; }

    public int? FormOfPayment { get; set; }

    public string TimeZone { get; set; }

    public bool? PreferredCommunicationMethodEmail { get; set; }

    public string NotificationFirstName { get; set; }

    public string NotificationLastName { get; set; }

    public string NotificationTitle { get; set; }

    public string NotificationEmail { get; set; }

    public bool? UpdateOnCreated { get; set; }

    public bool? UpdateOnCompleted { get; set; }

    public bool? UpdateOnDisptched { get; set; }

    public bool? UpdateOnAssigned { get; set; }

    public bool? UpdateOnReturn { get; set; }

    public bool? UpdateOnPartsOnOrder { get; set; }

    public bool? UpdateOnDelayed { get; set; }

    public bool? UpdateInCustomerPortal { get; set; }

    public bool? UpdateInCustomerEmail { get; set; }

    public string OtherFirstName { get; set; }

    public string OtherLastName { get; set; }

    public string OtherTitle { get; set; }

    public string OtherEmail { get; set; }

    public string SpecialInstructions { get; set; }

    public bool? UpdatedOnAcceptedInPortal { get; set; }

    public bool? UpdatedOnAssignedInPortal { get; set; }

    public bool? UpdatedOnDispatchInPortal { get; set; }

    public bool? UpdatedOnReturnInPortal { get; set; }

    public bool? UpdatedOnPartsOnOrderInPortal { get; set; }

    public bool? UpdatedOnFollowUpInPortal { get; set; }

    public bool? UpdatedOnPicturesInPortal { get; set; }

    public bool? UpdatedOnCompleteInPortal { get; set; }

    public bool? UpdatedOnDelayedInPortal { get; set; }

    public DateTime? InvoiceRecieved { get; set; }

    public bool? UpdatedOnAcceptedInEmail { get; set; }

    public bool? UpdatedOnAssignedInEmail { get; set; }

    public bool? UpdatedOnDispatchInEmail { get; set; }

    public bool? UpdatedOnReturnInEmail { get; set; }

    public bool? UpdatedOnPartsOnOrderInEmail { get; set; }

    public bool? UpdatedOnFollowUpInEmail { get; set; }

    public bool? UpdatedOnPicturesInEmail { get; set; }

    public bool? UpdatedOnCompleteInEmail { get; set; }

    public bool? UpdatedOnDelayedInEmail { get; set; }

    public bool IsWarrantyJob { get; set; }

    public long? ProjectId { get; set; }

    public string BubbleHeight { get; set; }

    public int? OfficeId { get; set; }

    public int? AssignedOfficeId { get; set; }

    public string Priority { get; set; }

    public long? AssignedJobId { get; set; }

    public string IPadStatus { get; set; }

    public bool? RelatedToFmpilot { get; set; }

    public long? TradeId { get; set; }

    public DateTime? DateCompleted { get; set; }

    public long? OwnerId { get; set; }

    public long? CompletedByUserId { get; set; }

    public string Ivr { get; set; }

    public string Pin { get; set; }

    public bool IsServiceChannelJob { get; set; }

    public virtual User BookedByUser { get; set; }

    public virtual User CompletedByUser { get; set; }

    public virtual Customer Customer { get; set; }
}