// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Oreolder.Models;

public partial class OreolderContext : DbContext
{
    public OreolderContext(DbContextOptions<OreolderContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Customer> Customer { get; set; }

    public virtual DbSet<Job> Job { get; set; }

    public virtual DbSet<User> User { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Customer__3214EC077F60ED59");

            entity.HasIndex(e => e.Id, "_dta_index_Customer_8_389576426__K1_5_6");

            entity.HasIndex(e => new { e.Id, e.CustomerType }, "_dta_index_Customer_8_389576426__K1_K8_5_6_7");

            entity.Property(e => e.AddedOnAccountsInPlay).HasColumnType("datetime");
            entity.Property(e => e.Amemail).HasColumnName("AMEmail");
            entity.Property(e => e.AmfirstName).HasColumnName("AMFirstName");
            entity.Property(e => e.AmlastName).HasColumnName("AMLastName");
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.CreditWorthy)
                .IsRequired()
                .HasDefaultValueSql("((1))");
            entity.Property(e => e.CustomerGuid).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CustomerPriceBookId).HasColumnName("CustomerPriceBookID");
            entity.Property(e => e.CustomerRepresentative)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.DiscountOnParts).HasColumnType("money");
            entity.Property(e => e.Email).HasMaxLength(250);
            entity.Property(e => e.HourlyLabour).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.IsNtechecked).HasColumnName("isNTEchecked");
            entity.Property(e => e.IsPochecked).HasColumnName("isPOchecked");
            entity.Property(e => e.Ivrnumber)
                .HasMaxLength(250)
                .HasColumnName("IVRNumber");
            entity.Property(e => e.Ivrpin)
                .HasMaxLength(250)
                .HasColumnName("IVRPin");
            entity.Property(e => e.LastUpdateOn).HasColumnType("datetime");
            entity.Property(e => e.MarkupOnParts).HasColumnType("money");
            entity.Property(e => e.NotificationEmail).HasMaxLength(50);
            entity.Property(e => e.NotificationFirstName).HasMaxLength(50);
            entity.Property(e => e.NotificationLastName).HasMaxLength(50);
            entity.Property(e => e.NotificationTitle).HasMaxLength(50);
            entity.Property(e => e.NteAmount).HasColumnType("money");
            entity.Property(e => e.OfficeId).HasDefaultValueSql("((0))");
            entity.Property(e => e.OtherEmail).HasMaxLength(200);
            entity.Property(e => e.Salutation).HasMaxLength(50);
            entity.Property(e => e.SubscriberId).HasMaxLength(50);
            entity.Property(e => e.TaxExemptNumber).HasMaxLength(250);
            entity.Property(e => e.TripCharges).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.WebSite).HasMaxLength(250);
        });

        modelBuilder.Entity<Job>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_WorkOrder");

            entity.HasIndex(e => new { e.JobTypeId, e.Id, e.CustomerId }, "_dta_index_Job_6_668581470__K3_K1_K2_51_52");

            entity.HasIndex(e => new { e.JobStatusId, e.Id, e.CustomerId, e.EquipmentId, e.StateId, e.Locked, e.OnDate, e.JobTypeId, e.StoreId }, "_dta_index_Job_6_668581470__K9_K1_K2_K8_K10_K55_K34_K3_K6_15_16_18_20_21_33_35_36_37_42_43_51");

            entity.HasIndex(e => new { e.JobStatusId, e.Id, e.CreatedOn }, "_dta_index_Job_6_668581470__K9_K1_K51_2_3_4_5_6_7_8_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31_32_33_34_");

            entity.HasIndex(e => new { e.JobStatusId, e.JobTypeId, e.Locked, e.StateId, e.CustomerId, e.EquipmentId, e.Id, e.StoreId }, "_dta_index_Job_6_668581470__K9_K3_K55_K10_K2_K8_K1_K6_15_16_18_20_21_33_34_35_36_37_42_43_51");

            entity.HasIndex(e => new { e.StateId, e.Id, e.CustomerId, e.EquipmentId }, "_dta_index_Job_8_1221579390__K10_K1_K2_K8_21_43_51");

            entity.HasIndex(e => new { e.CustomerId, e.EquipmentId, e.StateId, e.JobStatusId, e.Id, e.StoreId }, "_dta_index_Job_8_1221579390__K2_K8_K10_K9_K1_K6_3_15_16_17_18_20_21_33_34_35_36_37_42_43_51_55");

            entity.HasIndex(e => new { e.JobTypeId, e.CreatedOn, e.Id, e.ZipCode, e.StoreId, e.CustomerId, e.CreatedByUserId, e.CountryId, e.StateId, e.EquipmentId, e.JobStatusId, e.AdTypeId }, "_dta_index_Job_8_1221579390__K3_K51_K1_K14_K6_K2_K52_K11_K10_K8_K9_K7_15_16_17_18_20_21_26_27_28_32_33_34_35_37_42_49_56_57");

            entity.HasIndex(e => new { e.JobTypeId, e.CreatedOn, e.CreatedByUserId, e.CountryId, e.StateId, e.EquipmentId, e.JobStatusId, e.AdTypeId, e.Id, e.CustomerId, e.StoreId, e.ZipCode }, "_dta_index_Job_8_1221579390__K3_K51_K52_K11_K10_K8_K9_K7_K1_K2_K6_K14_15_16_17_18_20_21_26_27_28_32_33_34_35_37_49_56_57");

            entity.HasIndex(e => new { e.OfficeId, e.EquipmentId, e.Ponumber }, "nci_wi_Job_11B959C8E349FDBBE1B894AA8FFEC79A");

            entity.HasIndex(e => e.CustomerId, "nci_wi_Job_4E23AA7C65E80F08C82B3BB9EE1BEB65");

            entity.HasIndex(e => new { e.OfficeId, e.Ponumber }, "nci_wi_Job_57025E3A6D831369023E033CE52116F0");

            entity.HasIndex(e => new { e.OfficeId, e.JobStatusId, e.JobTypeId, e.OnDate }, "nci_wi_Job_86444126D16136A8D2EF468ACB7A665F");

            entity.HasIndex(e => e.OnDate, "nci_wi_Job_94E05C2A01816D7746ECE4DB8F1E7562");

            entity.HasIndex(e => new { e.OfficeId, e.Locked, e.JobTypeId, e.StateId, e.EquipmentId }, "nci_wi_Job_A2D5183532680FBB5F20C7DB88C7B3B1");

            entity.HasIndex(e => new { e.OfficeId, e.Locked, e.JobTypeId, e.JobStatusId }, "nci_wi_Job_D8685AB23A85531CD351C8382ADC6BDA");

            entity.HasIndex(e => new { e.StoreId, e.CreatedOn }, "nci_wi_Job_EA148D007FFE214111E219C19EB5FE02");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.AlternatePhone).HasMaxLength(50);
            entity.Property(e => e.ApartmentSuite).HasMaxLength(250);
            entity.Property(e => e.Ask).HasMaxLength(50);
            entity.Property(e => e.BubbleHeight)
                .HasMaxLength(50)
                .HasColumnName("bubbleHeight");
            entity.Property(e => e.BuzzerCode).HasMaxLength(50);
            entity.Property(e => e.CalledInBy).HasMaxLength(250);
            entity.Property(e => e.City).HasMaxLength(250);
            entity.Property(e => e.Color).HasMaxLength(250);
            entity.Property(e => e.ContactPerson).HasMaxLength(250);
            entity.Property(e => e.ContactPersonEmail).HasMaxLength(250);
            entity.Property(e => e.ContactPersonPhone).HasMaxLength(50);
            entity.Property(e => e.CountryId).HasDefaultValueSql("((1))");
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.DateCompleted).HasColumnType("datetime");
            entity.Property(e => e.DispatchedTime).HasColumnType("datetime");
            entity.Property(e => e.EmailAddress).HasMaxLength(250);
            entity.Property(e => e.Fax).HasMaxLength(50);
            entity.Property(e => e.FormOfPayment).HasDefaultValueSql("((1))");
            entity.Property(e => e.IPadStatus)
                .HasMaxLength(200)
                .HasColumnName("iPadStatus");
            entity.Property(e => e.InvoiceRecieved).HasColumnType("datetime");
            entity.Property(e => e.IsCow).HasColumnName("IsCOW");
            entity.Property(e => e.IsEmergency).HasDefaultValueSql("((0))");
            entity.Property(e => e.Ivr)
                .HasMaxLength(50)
                .HasColumnName("IVR");
            entity.Property(e => e.LastUpdateOn).HasColumnType("datetime");
            entity.Property(e => e.Latitude).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.LinkJobId)
                .HasMaxLength(50)
                .HasColumnName("LinkJobID");
            entity.Property(e => e.Longtitude).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.Make).HasMaxLength(250);
            entity.Property(e => e.Model).HasMaxLength(250);
            entity.Property(e => e.NotificationEmail).HasMaxLength(50);
            entity.Property(e => e.NotificationFirstName).HasMaxLength(50);
            entity.Property(e => e.NotificationLastName).HasMaxLength(50);
            entity.Property(e => e.NotificationTitle).HasMaxLength(50);
            entity.Property(e => e.Nteamount)
                .HasColumnType("money")
                .HasColumnName("NTEAmount");
            entity.Property(e => e.OfficeId).HasDefaultValueSql("((0))");
            entity.Property(e => e.OnDate).HasColumnType("date");
            entity.Property(e => e.OtherEmail).HasMaxLength(200);
            entity.Property(e => e.OtherFirstName).HasMaxLength(50);
            entity.Property(e => e.OtherLastName).HasMaxLength(50);
            entity.Property(e => e.OtherTitle).HasMaxLength(50);
            entity.Property(e => e.Phone).HasMaxLength(50);
            entity.Property(e => e.Pin)
                .HasMaxLength(50)
                .HasColumnName("PIN");
            entity.Property(e => e.Ponumber)
                .HasMaxLength(50)
                .HasColumnName("PONumber");
            entity.Property(e => e.Priority).HasMaxLength(150);
            entity.Property(e => e.ProjectId).HasColumnName("projectId");
            entity.Property(e => e.RelatedToFmpilot).HasColumnName("RelatedToFMPilot");
            entity.Property(e => e.Street).HasMaxLength(250);
            entity.Property(e => e.TimeZone).HasMaxLength(250);
            entity.Property(e => e.WorkOrder2).HasMaxLength(50);
            entity.Property(e => e.ZipCode).HasMaxLength(50);

            entity.HasOne(d => d.BookedByUser).WithMany(p => p.JobBookedByUser)
                .HasForeignKey(d => d.BookedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Job_User");

            entity.HasOne(d => d.CompletedByUser).WithMany(p => p.JobCompletedByUser)
                .HasForeignKey(d => d.CompletedByUserId)
                .HasConstraintName("FK_Job_CompletedByUserId");

            entity.HasOne(d => d.Customer).WithMany(p => p.Job)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Job_Customer");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_User_Id");

            entity.HasIndex(e => e.Id, "_dta_index_User_8_837578022__K1_3");

            entity.Property(e => e.Cell).HasMaxLength(250);
            entity.Property(e => e.City).HasMaxLength(250);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.CurrentBoardType).HasDefaultValueSql("((1))");
            entity.Property(e => e.Email).HasMaxLength(1000);
            entity.Property(e => e.GreaterThanNteamountEntryAllowed)
                .HasDefaultValueSql("((1))")
                .HasColumnName("GreaterThanNTEAmountEntryAllowed");
            entity.Property(e => e.HiringDate).HasColumnType("datetime");
            entity.Property(e => e.LastLoginDate).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedOn).HasColumnType("datetime");
            entity.Property(e => e.PasswordChangedOn).HasColumnType("datetime");
            entity.Property(e => e.Phone).HasMaxLength(250);
            entity.Property(e => e.Ssn)
                .HasMaxLength(250)
                .HasColumnName("SSN");
            entity.Property(e => e.TimeZone).HasMaxLength(250);
            entity.Property(e => e.Username).HasMaxLength(1000);
            entity.Property(e => e.ZipCode).HasMaxLength(50);

            entity.HasOne(d => d.Customer).WithMany(p => p.User)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_User_Customer");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}