// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Oreolder.Models;

public partial class User
{
    public long Id { get; set; }

    public Guid UserGuid { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int RoleId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Address { get; set; }

    public string ZipCode { get; set; }

    public string City { get; set; }

    public int? StateId { get; set; }

    public string Cell { get; set; }

    public string Phone { get; set; }

    public bool? ChangeJobTypes { get; set; }

    public int? AllowedJobTypeId { get; set; }

    public bool? GreaterThanNteamountEntryAllowed { get; set; }

    public bool Active { get; set; }

    public int CurrentBoardType { get; set; }

    public bool Deleted { get; set; }

    public string LastIpAddress { get; set; }

    public DateTime CreatedOn { get; set; }

    public long CreatedByUserId { get; set; }

    public DateTime LastUpdatedOn { get; set; }

    public DateTime? LastLoginDate { get; set; }

    public long LastUpdatedByUserId { get; set; }

    public long? ContractorId { get; set; }

    public DateTime? HiringDate { get; set; }

    public string Ssn { get; set; }

    public string TimeZone { get; set; }

    public string FilterPanelHistory { get; set; }

    public long? TechnicianId { get; set; }

    public long? CustomerId { get; set; }

    public int? Department { get; set; }

    public DateTime? PasswordChangedOn { get; set; }

    public int? OfficeId { get; set; }

    public bool CorporateUser { get; set; }

    public int? BoardRefreshTime { get; set; }

    public bool? ShowOnStatusBoard { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<Job> JobBookedByUser { get; set; } = new List<Job>();

    public virtual ICollection<Job> JobCompletedByUser { get; set; } = new List<Job>();
}